LemmyNet/lemmy-js-client

src/http.ts
As per https://github.com/LemmyNet/lemmy/blob/4b92e35edc16af87c858d5ce386014e09e2714e6/crates/api/src/local_user.rs#L902
=> Fix markAllAsRead response type

src/interfaces/api/site.ts
=> Add field Site.default_theme in missing places

package.json, src/interfaces/api/comment.ts, src/interfaces/api/community.ts, src/interfaces/api/person.ts, src/interfaces/api/post.ts, src/interfaces/api/site.ts
Tested this with lemmy-ui, works fine without any changes.
=> Use enum types

src/http.ts, src/interfaces/api/community.ts, src/interfaces/views.ts
Reverts LemmyNet/lemmy-js-client#52
=> Revert "Add follow pending."

src/interfaces/api/site.ts, src/interfaces/others.ts, src/interfaces/source.ts, src/interfaces/views.ts
See https://github.com/LemmyNet/lemmy/pull/2313
=> Add Modlog Filters

src/interfaces/source.ts
https://github.com/LemmyNet/lemmy/pull/2261
=> Rename post.embed_html field to embed_video_url

src/interfaces/api/site.ts, src/interfaces/source.ts, src/interfaces/views.ts
See https://github.com/LemmyNet/lemmy/pull/2548
=> Add Tagline structs

src/interfaces/api/site.ts, src/interfaces/source.ts, src/interfaces/views.ts
=> Update Taglines pt 2

src/interfaces/source.ts, yarn.lock
https://github.com/LemmyNet/lemmy/pull/2604
=> Add LocalSite.registration_mode

src/interfaces/api/site.ts
Forgot to change these in https://github.com/LemmyNet/lemmy-js-client/pull/96. Would be really nice if there was a way to test these changes before merging and publishing.
=> Udate CreateSite/EditSite structs for registration mode

README.md
I noticed a small error in the docs while working on #108.
=> docs: Fix incorrect code sample in README

src/http.ts, src/interfaces/api/custom_emoji.ts, src/interfaces/api/index.ts, src/interfaces/api/site.ts, src/interfaces/others.ts, src/interfaces/source.ts, src/interfaces/views.ts, src/websocket.ts
See https://github.com/LemmyNet/lemmy/pull/2616
=> Add Custom Emojis Support

src/http.ts
Forgot to add this one. No point in adding websocket, since that's going away.
=> Adding new distinguish comment.

src/http.ts
These are necessary for the lemmy-ui rework I'm doing.
=> Add missing response types in http client.

package.json, src/http.ts
I did this wrong the first time.
=> Better error wrapping.

package.json, src/http.ts, src/websocket.ts
=> Remove BigInt

src/http.ts
=> Add default value to client functions that have optional form data or query params

src/http.ts
=> Make fetch function optional

src/types/Community.ts, src/types/LocalUser.ts, src/types/Person.ts, src/types/SaveUserSettings.ts
Also adds a few new fields that got added to Person and Community.
=> Add open links in new tab.

src/types/LocalUser.ts, src/types/SaveUserSettings.ts
error on lemmy-ui:
https://woodpecker.join-lemmy.org/repos/135/pipeline/1232/5
required for:
https://github.com/LemmyNet/lemmy-ui/pull/1640
https://github.com/LemmyNet/lemmy/pull/3377
pretty sure this is what I need to do to get this working, lmk!
=> changes for blur_nsfw/auto_expand

.eslintrc.json, src/http.ts
I suggest simply wrapping the lines in an Error object.
=> #186 wrap bare strings to Error object

src/http.ts
Depends on https://github.com/LemmyNet/lemmy/pull/4121. Not sure whats the best way to test this change.
=> Add logout endpoint (fixes #206)

src/types/CommentReplyView.ts, src/types/CommentView.ts, src/types/PersonMentionView.ts, src/types/PersonView.ts, src/types/PostView.ts, src/types/SaveUserSettings.ts
- Backend PR: https://github.com/LemmyNet/lemmy/pull/4165
=> Adding `creator_is_admin` to various views.

package.json, src/http.ts, yarn.lock
Reverts LemmyNet/lemmy-js-client#216
=> Revert "Upgrading deps, removing cross_fetch."

src/types/CommunityAggregates.ts
Blocks https://github.com/LemmyNet/lemmy/pull/4166
=> Add local_subscribers field to CommunityAggregates

src/types/CommunityAggregates.ts
Reverts LemmyNet/lemmy-js-client#221
=> Revert "Add local_subscribers field to CommunityAggregates"

src/types/CommunityAggregates.ts
Changed https://github.com/LemmyNet/lemmy-js-client/pull/221
=> Add subscribers_local to community aggregates

src/types/Community.ts, src/types/CreateCommunity.ts, src/types/CreateSite.ts, src/types/EditCommunity.ts, src/types/EditSite.ts, src/types/LocalSite.ts
See https://github.com/LemmyNet/lemmy/pull/4393
=> Integrate changes from lemmynsfw fork

src/types/Community.ts, src/types/CommunityAggregates.ts, src/types/CreateCommunity.ts, src/types/CreateSite.ts, src/types/EditCommunity.ts, src/types/EditSite.ts, src/types/GetPersonDetailsResponse.ts, src/types/LocalSite.ts
Removes some of the prematurely merged items also.
Wait until those back-end PRs are merged into main first.
=> Updating types from lemmy main branch.

package.json, pnpm-lock.yaml, src/http.ts
Resolves #250
~~I am having trouble testing this, I am getting errors when trying to `pnpm i ../lemmy-js-client` in my project.~~
Tested (including image upload changes) and working well with Voyager.
=> Remove dependencies

README.md
Use a more detailed example in the readme.
=> Better readme example.

src/types/LemmyErrorType.ts, src/types/Register.ts
Once this is merged, I'll start the 0.19.4 release of just this client, and do PRs for the other repos to use it.
=> Updating changes from main before a 0.19.4 release.

renovate.json
Adding a schedule cause the constant updates are annoying.
=> Adding renovate schedule.

src/http.ts
=> Adding optional auth endpoints.

src/http.ts
Fixes #465
[swagger.json](https://github.com/user-attachments/files/18593061/swagger.json)
=> Add tags #465

README.md
=> Adding OpenAPI doc generation, and dev instructions.

src/http.ts
Required for tests in https://github.com/LemmyNet/lemmy/pull/5496
=> Add createCommunityReport and resolveCommunityReport
