src/http.ts, src/interfaces/api/community.ts, src/interfaces/api/site.ts, src/interfaces/others.ts, src/interfaces/source.ts, src/interfaces/views.ts, src/websocket.ts
Dont know how to test this, but this removes all mentions of the term category/categories according to `rg`.
=> Remove categories

src/interfaces/views.ts
It was removed from the API: https://github.com/LemmyNet/lemmy/blob/dd5835fb6ee210af78ba876bf3e9f37ea1db521b/crates/db_views/src/site_view.rs#L10
@LouisMarotta has found this inconsistency
=> Remove creator from SiteView

src/http.ts
Makes it so that people viewing the API docs will also see the endpoints.
=> Adding endpoint comments. Fixes #50

README.md
The links did not work directy out of the repository on GitHub. Fixed this by adding the full path inclusive domain.
=> Fixed links to Documentation

src/http.ts, src/interfaces/aggregates.ts, src/interfaces/api/post.ts, src/interfaces/api/site.ts, src/interfaces/others.ts, src/interfaces/source.ts, src/interfaces/views.ts, src/websocket.ts
See https://github.com/LemmyNet/lemmy/pull/2585
=> Add FeaturePost support

package.json, src/http.ts, src/interfaces/others.ts, src/utils.ts, tsconfig.json, yarn.lock
This is a PR to take care of #107.
Besides implementing image uploading on the HTTP client, I also updated `node-fetch` to the latest v3.x version. 
To get around the ESM-only module constraint, I followed some advice in the package's docs.
From [`node-fetch`'s docs:](https://www.npmjs.com/package/node-fetch)
> Alternatively, you can use the async import() function from CommonJS to load node-fetch asynchronously:
> ```javascript
> // mod.cjs
> const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
> ```
Since the Typescript compiler turns dynamic imports into requires if the module option in tsconfig.json is set to CommonJS (like this project), a little bit of trickery was required to get the import working properly. That weirdness is a small function …
=> feat: add image upload method to http client

src/http.ts, src/interfaces/api/comment.ts, src/interfaces/others.ts, src/websocket.ts
I noticed that [get comment is a part of the API](https://github.com/LemmyNet/lemmy/blob/main/crates/api_crud/src/comment/read.rs#L13-L42) but isn't included in the client. This PR adds it to the client.
=> Add getComment to client

src/http.ts, src/websocket.ts
I have a library that's dependent on the js client and it was getting errors because `bigint`s cannot be serialized by `JSON.stringify` by default. This should fix that.
=> Fix body not serializing because of bigint

src/http.ts
Currently in the lemmy-ui code (since it uses websocket), we are manually checking `if (msg.error) {...`  . 
In the switch to http tho, it'll be nice to throw an exception not just for connection issues, but for any of those responses as well. 
This solution comes from [here](https://stackoverflow.com/questions/56295606/typescriptor-javascript-fetch-api-async-await-error-handling), which says you must check the `response.ok`, and throw an exception when its not. 
In switching over lemmy-ui to use the HTTP client, I plan to do something like this for failed http requests:
```ts
export function apiWrapper<ResponseType>(
res: ResponseType
): RequestState<ResponseType> {
try {
return {
state: "success",
data: res,
};
} catch (error) {
return {
state: "failed",
msg: error,
};
}
}
```
=> Making the http `{"error": "..."}` json into a string exception.

package.json, src/http.ts, tsconfig.json
It turns out putting the the `private` keyword in front of class properties is just a nicety from typescript that doesn't stop them from being accessed. I replaced them with [the `#` prefix](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).
This should make it significantly easier to make a wrapper for the HTTP client in the UI project, as well as avoid exposing internals to users of the library.
=> Make private class properties actually private

src/http.ts
`main` branch rn doesnt care about extra trailing slashes in the instance url, but http servers do, because the request urls ends up lookin like `https://instance.yip//api/v3/blablabla`. this adds some regex (specifically, `/\/+$/`) to grab and remove em.
=> remove trailing slashes from instance url

src/http.ts
Currently, when a server responds with 413 content too large for an image upload, then it breaks Lemmy-ui. This PR adds a special `msg` for the 413 case, which can be handled in the UI.
Related PR in Lemmy-UI: https://github.com/LemmyNet/lemmy-ui/pull/1675
=> Handle 413 response on image uploads

src/http.ts, src/types/others.ts
I couldn't find info for the response JSON on the delete, so I'm just typing it `any`
=> Adding deleteImage endpoint. Fixes #193

src/http.ts
This still has the wrong response, 
Unrelated tbh `MarkPostAsRead` Should be now `MarkPostsAsRead` (minor, no strong feelings)
Also the "deprecated" post_id should have been straight up removed, Not sure why this short backwardscompatiblity was kept. It's very easy to change from Single to List. (I treat deprecated stuff in My LemmyApi as removed anyway easier to handle future mappings)
=> Fix MarkPostAsRead, wrong response

src/http.ts, src/other_types.ts
These use the same header/cookie auth now as all other api endpoints, so there is no reason for separate auth param.
=> Remove separate auth params for image endpoints

src/http.ts
pict-rs returns an empty response with status 204 No Content for the delete endpoint. Thats why https://github.com/LemmyNet/lemmy/pull/4150 is currently failing as the library expects a valid json response.
https://git.asonix.dog/asonix/pict-rs/src/branch/main/src/lib.rs#L758
=> Properly handle pictrs delete image response

src/types/LemmyErrorType.ts
Ran the `copy_generated_types` script again, it picked up this new error type.
=> Adding an error type.

src/http.ts
This endpoint had incorrect jsdoc, I parse this for my openapi3 spec so its important for me, that this is right.
=> Fix jsdoc comment for listCommentLikes

package.json
pnpm always aggressively adds the package manager field to package.json if it's not there already. Making a PR to add the field so pnpm will stop.
=> Add pacakge manager to package.json

README.md
`pnpm add` supports adding local dependencies easily. Since this library uses `pnpm` now, `yalc` is unnecessary.
=> Replace yalc recommendation for instructions to do the same thing with pnpm

src/http.ts
This is currently missing on https://join-lemmy.org/api/classes/LemmyHttp.html#logout
=> Add missing docs for logout endpoint

src/http.ts
`0`, `false` and `""` currently become `None` on the server.
Noticed this trying to list comments with `max_depth: 0`.
=> Allow falsey get parameter values

src/types/LemmyErrorType.ts
One error type wasn't in use anymore.
=> Updating types from main.

src/http.ts
This PR adds support for aborting requests. This is best practice to promptly clean up asyncronous requests as e.g. components are unmounted.
`AbortController` is supported in all modern browsers, and all currently supported Node versions (Node 18 is currently minimum LTS version, `AbortController` added in Node 15) - https://nodejs.org/en/about/previous-releases
This PR requires no code changes for end users. Abortable requests is entirely optional.
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://dev.to/viclafouch/cancel-properly-http-requests-in-react-hooks-and-avoid-memory-leaks-pd7
=> Add support for request abort signal

.gitignore, eslint.config.mjs, package.json, pnpm-lock.yaml, src/http.ts, src/other_types.ts, tsoa.json
Here's its sample output, you can test it by importing this `json` file into : https://editor.swagger.io
[swagger.json](https://github.com/user-attachments/files/18507757/swagger.json)
You can generate this file by running `pnpm tsoa`
This works, but has some limitations. I can't figure out how to add top level (maybe called controller, or server), documentation. This is kind of crucial because you need to know that : 
- The errors are left out for now, as they'd require some work.
- How to use it as a javascript library as described here: https://github.com/LemmyNet/lemmy-js-client#usage
My next steps are to add a swagger generator to the joinlemmy-site repo.
cc @MV-GH @SleeplessOne1917 @Nutomic
=> Auto-generating swagger / OpenAPI docs using tsoa and redocly

src/http.ts
Corrects the current "descriptions" as summaries.
Half of them end with dot, the other without. A decision should be made on which one.  (imo A summary shouldnt need one)
Closes #466
=> Add summaries to endpoints #466

tsoa.json
See https://github.com/lukeautry/tsoa/issues/909#issuecomment-786839358
I don't know the difference between ds9/Enterprise/Voyager, so I couldn't specify the distinction.
=> Adds Server endpoints to the spec

package.json, src/types/Community.ts, src/types/Person.ts, src/types/Site.ts
https://github.com/LemmyNet/lemmy/pull/5393
=> Rename actor_id columns to ap_id

src/http.ts
Changes for: https://github.com/LemmyNet/lemmy/pull/5534 and https://github.com/LemmyNet/lemmy/pull/5535
`markPrivateMessageAsRead` is unrelated.
=> Image upload response, /account/saved, markPrivateMessageAsRead

package.json, pnpm-lock.yaml, src/http.ts
Webpack tries to import node stuff from "@tsoa/cli" when importing "tsoa".
=> Use @tsoa/runtime imports

src/http.ts
[This commit](https://github.com/christianjuth/lemmy-js-client/commit/e284e7df14c7f0814ced5e01efb8b6185c64df1d) added support for aborting requests via signal, but it's not available on Lemmy 0.19.X. This backports that change so earlier versions of Lemmy can benefit from this optimization.
=> Backport support for request abort signal

scripts/copy_generated_types_from_lemmy.sh
I was testing with the beginning of this file commented out, so it already started with `LemmyErrorType.ts` correctly formatted. But when generating things from scratch it would be unformatted and the regex wouldnt match. So it needs an explicit format call.
=> Format error file before regex
